name: remind_to_relax
description: "A mindful meditation app to help you relax and stay focused"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  vector_math: ^2.1.4
  webview_flutter: ^4.9.0
  flutter_animate: ^4.1.1+1
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  liquid_swipe: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/playstore.png
